version: '3.8'

services:
  wqbrain:
    build: .
    container_name: wqbrain
    volumes:
      - ./data:/app/data  # 挂载本地目录 ./data
      #- wqbrain_data:/app/data
    env_file: .env  # 从 .env 文件加载环境变量
    user: appuser
    command: python main.py

volumes:
  wqbrain_data:
