FORMULAS = [
{"delay": 1, "decay": 0, "neutralization": "INDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 0, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 9, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 10, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 11, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 12, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 13, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 14, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 15, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 16, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 17, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 18, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 19, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 20, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 25, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 30, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 35, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 40, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 8, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 63)"},
{"delay": 1, "decay": 0, "neutralization": "INDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-ts_rank(fn_liab_fair_val_l1_a, 252)"},
{"delay": 1, "decay": 0, "neutralization": "INDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-if_else(ts_rank(fn_liab_fair_val_l1_a, 63) > 0.8, 1, 0) "},
{"delay": 1, "decay": 0, "neutralization": "INDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
{"delay": 1, "decay": 0, "neutralization": "SECTOR",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
{"delay": 1, "decay": 0, "neutralization": "MARKET",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
{"delay": 1, "decay": 0, "neutralization": "SUBINDUSTRY",
     "truncation": 0.07, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
{"delay": 1, "decay": 0, "neutralization": "SUBINDUSTRY",
     "truncation": 0.05, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
{"delay": 1, "decay": 0, "neutralization": "SUBINDUSTRY",
     "truncation": 0.03, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
{"delay": 1, "decay": 0, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
{"delay": 1, "decay": 1, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
{"delay": 1, "decay": 2, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
{"delay": 1, "decay": 3, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
{"delay": 1, "decay": 4, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
{"delay": 1, "decay": 5, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
    {"delay": 1, "decay": 12, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
    {"delay": 1, "decay": 9, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
{"delay": 1, "decay": 8, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
{"delay": 1, "decay": 7, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
{"delay": 1, "decay": 6, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
    {"delay": 1, "decay": 11, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
    {"delay": 1, "decay": 10, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "ts_rank(operating_income / close, 252)"},
    {"delay": 1, "decay": 10, "neutralization": "SUBINDUSTRY",
     "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-returns"},
    {"delay": 1, "decay": 5, "neutralization": "SUBINDUSTRY", "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-returns"},
    {"delay": 1, "decay": 12, "neutralization": "SUBINDUSTRY", "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-returns"},
    {"delay": 1, "decay": 3, "neutralization": "SUBINDUSTRY", "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-returns"},
    {"delay": 1, "decay": 8, "neutralization": "SUBINDUSTRY", "truncation": 0.06, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-returns"},
    {"delay": 1, "decay": 8, "neutralization": "SUBINDUSTRY", "truncation": 0.04, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-returns"},
    {"delay": 1, "decay": 8, "neutralization": "SUBINDUSTRY", "truncation": 0.02, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-returns"},
    {"delay": 1, "decay": 8, "neutralization": "SUBINDUSTRY", "truncation": 0.08, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-returns"},
    {"delay": 1, "decay": 8, "neutralization": "SUBINDUSTRY", "truncation": 0.1, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-returns"},
    {"delay": 1, "decay": 8, "neutralization": "SUBINDUSTRY", "truncation": 0.12, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "-returns"},
    "group_zscore(ts_zscore(fnd6_mfma1_dp,600),subindustry)",
    "group_neutralize(power(rank(assets - group_mean(assets, 1, subindustry)), 3), bucket(rank(cap), range='0,1,0.1'))",
    {"delay": 1, "decay": 10, "neutralization": "SECTOR", "truncation": 0.01, "pasteurization": "ON",
     "unitHandling": "VERIFY", "nanHandling": "OFF", "language": "FASTEXPR", "visualization": False,
     "regular": "trade_when(pcr_oi_270 < 1, implied_volatility_call_270-implied_volatility_put_270, -1)"},
]
